feat: can work with requests without params, JsonRpc.C…
tochka-public/Tochka.JsonRpc pull request #114
Opened 2024-08-22 10:52 UTC by OlgaStarkova-Tochka

JsonRpc.Server can work with requests without params, JsonRpc.Client has methods without params

2024-08-27 11:27 UTC, Rast1234 requested changes

2024-08-27 11:27 UTC, Rast1234 commented on src/Tochka.JsonRpc.Common/Models/Request/Request.cs
> +/// Request with typed params
это не правда

2024-08-27 11:27 UTC, Rast1234 commented on src/Tochka.JsonRpc.Common/Tochka.JsonRpc.Common.csproj
> +  <ItemGroup>
это лишнее

2024-08-27 11:27 UTC, Rast1234 commented on src/Tochka.JsonRpc.Server/Binding/JsonRpcParamsParser.cs
> -            null => ParseNoParams(bindingStyle),
у тебя не подключен кодстайл. иначе бы он тебе подсветил, что теперь этот метод не используется и его надо удалить. подключи, переформатируй все затронутые файлы и поправь все ошибки которые всплывут

2024-08-27 11:27 UTC, Rast1234 commented on src/Tochka.JsonRpc.Server/Binding/JsonRpcParamsParser.cs
> -        var hasParamsNode = rawCall.RootElement.TryGetProperty(JsonRpcConstants.ParamsProperty, out _);
а почему это ушло, вместе с ParseNoParams? в зависимости от него логика отличается и в JsonRpcParameterBinder есть ветки под это тоже

2024-09-16 09:41 UTC, OlgaStarkova-Tochka commented on src/Tochka.JsonRpc.Common/Models/Request/Request.cs
> +/// Request with typed params
fix

2024-09-16 09:41 UTC, OlgaStarkova-Tochka commented on src/Tochka.JsonRpc.Common/Tochka.JsonRpc.Common.csproj
> +  <ItemGroup>
fix

2024-09-16 09:42 UTC, OlgaStarkova-Tochka commented on src/Tochka.JsonRpc.Server/Binding/JsonRpcParamsParser.cs
> -            null => ParseNoParams(bindingStyle),
подключила, поправила всё в соответствии с кодстайлом

2024-09-16 09:49 UTC, OlgaStarkova-Tochka commented on src/Tochka.JsonRpc.Server/Binding/JsonRpcParamsParser.cs
> -        var hasParamsNode = rawCall.RootElement.TryGetProperty(JsonRpcConstants.ParamsProperty, out _);
вот тут не поняла, у нас сейчас запросы вообще без параметров и с null в параметре должны обрабатываться одинаково

2024-09-17 15:28 UTC, Rast1234 approved these changes

2024-09-23 19:47 UTC, merged